# Permalinks
permalink:           pretty


# Setup
title:               Jiang Zerui
tagline:             '极简-Live a little'
description:         ''
url:                 http://jiangzerui.cn
baseurl:             https://jiangzerui.github.io
paginate:            10
repo:

# About/contact
author:
  name:              J.Jiang
  url:               https://jiangzerui.cn
  email:             stonefavorite@126.com

# Custom vars
version:             1.0.0
