# Permalinks
permalink:           pretty


# Setup
title:               Jiang Zerui
tagline:             '极简-Homepage'
description:         'zerui 的个人站点'
url:                 http://jiangzerui.cn
baseurl:            https://jiangzerui.github.io
paginate:            5

# About/contact
author:
  name:              J.Jiang
  url:               https://jiangzerui.cn
  email:             stonefavorite@126.com

# Custom vars
version:             1.0.0
